language: elixir

elixir:
  - 1.10
  - 1.9
  - 1.8
  - 1.7

otp_release:
  - '22.2'

before_script:
  - mix compile –warnings-as-errors
  - mix credo --strict
  - if [[ "$TRAVIS_ELIXIR_VERSION" =~ "1.10" ]]; then mix format mix.exs "{config,clients,games,lib,test}/**/*.{ex,exs}" --check-formatted; fi
